### PR TITLE
Audit cool_faces crate

### PR DESCRIPTION
**Pull request by robjtede**

### CODE REVIEW

**Comment by bholley** [comment]
I apologize, but we can't accept externally-contributed audits into our set, Would be awesome if actix were to deploy its own set though, and we'd happily include it in the registry.

**Comment by robjtede** [comment]
Hey. That's fine, I maybe missed in the documentation exactly how to "contribute" audits.

**Comment by bholley** [comment]
They way to contribute audits is to submit them to an instance for an organization you're involved with. That allows anyone to pull in your audits if they're willing to trust your organization. This is somewhat covered in the [overview](https://mozilla.github.io/cargo-vet/how-it-works.html) as well as the documentation on [curating an audit set](https://mozilla.github.io/cargo-vet/curating-your-audit-set.html).

**Comment by robjtede** [comment]
Appreciate the links for future reference.

I'll be honest, this PR more or less came out of a joke at EuroRust, so thanks for taking the time to respond. 👍

**Pull request closed without merging**
