### PR TITLE
Avoid writing `config.toml` and other files if no significant changes.

### PR DESCRIPTION
**Pull request by anforowicz**
After this commit `audits.toml`, `config.toml`, and `imports.lock` will not be written if their contents wouldn't have changed ("contents" in a business logic sense - ignoring comments and/or formatting differences).

Fixes https://github.com/mozilla/cargo-vet/issues/589

### CODE REVIEW

**Comment by anforowicz** [comment]
Ooops... I neglected to update test expectations... Let me fix this...

**Review by mystor — CHANGES_REQUESTED** [review]
As I explain in https://github.com/mozilla/cargo-vet/issues/589#issuecomment-1998315628, I don't think this is the approach we want to take. Marking as requesting changes for now.

**Comment by anforowicz** [comment]
Abandoning this PR based on https://github.com/mozilla/cargo-vet/issues/589#issuecomment-1998315628

**Pull request closed without merging**
